<?php
namespace JesseyChen\Test;
use \Illuminate\Support\Facades\Facade as LaravelFacade;

class Facade extends LaravelFacade
{
    protected static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'qiniu';
    }
}